// auth
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const LOAD_USER = "LOAD_USER";
//form
export const CREATE_FORM = "CREATE_FORM";
export const FORM_LOADING = "FORM_LOADING";
export const FORM_ERROR = "FORM_ERROR";
export const GET_ALL_USER_FORMS = "GET_ALL_USER_FORMS";
export const GET_FORM = "GET_FORM";
export const UPDATE_FORM_TITLE = "UPDATE_FORM_TITLE";
export const ADD_FIELD = "ADD_FIELD";
export const DELETE_FIELD = "DELETE_FIELD";
export const UPDATE_FIELD = "UPDATE_FIELD";
export const SUBMIT_FORM = "SUBMIT_FORM";
export const ADD_FIELD_OPTION = "ADD_FIELD_OPTION";
export const DELETE_FIELD_OPTION = "DELETE_FIELD_OPTION";
export const UPDATE_FIELD_OPTIONS = "UPDATE_FIELD_OPTIONS";
export const ADD_FORM_LANGUAGE = "ADD_FORM_LANGUAGE";
export const REMOVE_FORM_LANGUAGE = "REMOVE_FORM_LANGUAGE";
export const GET_FORM_TRANSLATION = "GET_FORM_TRANSLATION";
export const TRANSLATE_FIELD_OPTIONS = "TRANSLATE_FIELD_OPTIONS";
export const TRANSLATE_FIELD_QUESTION = "TRANSLATE_FIELD_QUESTION";
export const UPDATE_FIELD_GROUP = "UPDATE_FIELD_GROUP";
export const UPDATE_GROUP_TYPE = "UPDATE_GROUP_TYPE";
export const UPDATE_FIELD_OPTIONS_VARIABLES = "UPDATE_FIELD_OPTIONS_VARIABLES";
export const DELETE_FORM = "DELETE_FORM";
export const GET_FORM_FOR_SUBMISSION = "GET_FORM_FOR_SUBMISSION";

//SUBMISSION
export const SUBMISSION_LOADING = "SUBMISSION_LOADING";
export const SUBMISSION_ERROR = "SUBMISSION_ERROR";
export const GET_SUBMISSIONS = "GET_SUBMISSIONS";
